#ifndef PROPS_H
#define PROPS_H

#define PROP_APPNAME 1
#define PROP_USERNAME 2
#define PROP_PROTOCOL 3
#define PROP_ERROR 4
#define PROP_CHANNEL 5
#define PROP_PASSWORD 6
#define PROP_AVATARS 7
#define PROP_UPDATETIME 8
#define PROP_CLIENT 9
#define PROP_SERIAL 10
#define PROP_EMAIL 11
#define PROP_LOGONOFF 12
#define PROP_DURATION 13
#define PROP_GUEST 14
#define PROP_SERVERTYPE 15
#define PROP_BIZCARD 16
#define PROP_NEW_PASSWORD 20
#define PROP_PRIV 22
#define PROP_ASLEEP 23
#define PROP_EX_HTTP_SERVER 24
#define PROP_SCRIPT_SERVER 25
#define PROP_SMTP_SERVER 26
#define PROP_MAIL_DOMAIN 27
#define PROP_NEW_USERNAME 28
#define PROP_IN_HTTP_SERVER 29
#define PROP_INVENTORY 30

#endif

