#ifndef H_VAR_ERROR
#define H_VAR_ERROR

#define VAR_OK 0
#define VAR_BAD_USER 1
#define VAR_MAX_ORDINARY 2
#define VAR_MAX_PRIORITY 3
#define VAR_FATAL 5
#define VAR_BAD_PROTOCOL 6
#define VAR_BAD_CLIENTSW 7
#define VAR_BAD_SERIAL 9
#define VAR_TAKEN_SERIAL 10
#define VAR_TAKEN_USER 11
#define VAR_NO_SUCH_USER 12
#define VAR_BAD_PASSWORD 13
#define VAR_BAD_ACCOUNT 14
#define VAR_NOT_LOGGEDON 15
#define VAR_BAD_IPADDRESS 16
#define VAR_LOGGEDON 17
#define VAR_ROOM_FULL 21
#define VAR_UNEXPECTED 100 | 101 | 102 | 103
#define VAR_UNREACHABLE 104 | 105 | 106 | 107
#define VAR_SHUTTING_DOWN 201
#define VAR_RECONNECTING 202
#define VAR_DISCONNECTED 203
#define VAR_LOST_CONNECTION 204
#define VAR_SINGLE_USER 205

#endif